version: "3.8"
services:
  frontend:

  backend:
  
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
    - 16686:16686
    - 6831:6831/udp

  elasticsearch:
    image:
    ports:
    environment:
    volumes:
      - elasticadata:/usr/share/elasticsearch/data

  kibana:
    image:
    ports:
    environment:

volumes:
  elasticdata: